---
title: "design for point dendrometer study"
author: ""
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
```{r libraries, echo=F}
library(tidyverse)
library(viridis)
library(ggplot2)
library(plotly)
```

```{r species list, echo=F}

#read dendro_inc_clean.csv

dendro_inc_clean <- read.csv("data/HKK-dendro/dendro_inc_clean.csv")
load("data/HKK-dendro/dendrobyband.RData")
shortlist<-c("DIPTAL", "HOPEOD", "TETRNU", "VATIHA", "CHUKTA", "POLYVI", "DIOSWI", "CROTRO", "SACCLI", "LAGETO", "GARUPI", "AFZEXY")

sp.list <- read.csv("data/HKK-dendro/point_dendro_sp.csv")

sp.list
```
```{r species chars, echo=F}

#make dendroband plots across years for each species

#subset data to these species
point_sp<-dendro_inc_clean %>%
filter(sp %in% shortlist)

point_sp_tree<-trees %>%
filter(SPCODE.UPDATE %in% shortlist)

spagplot_ind<-ggplot() +
  geom_line(data = point_sp, aes(x=((Cno-3)/2)+2009, y=inc_annual, group=Tag), alpha=0.5) +
  geom_line(data=point_sp %>% group_by(sp,Cno) %>% dplyr::summarise(mean_inc=mean(inc_annual, na.rm=T)), aes(x=((Cno-3)/2)+2009, y=mean_inc), col="red")+
  geom_line(data=point_sp %>% group_by(sp,Cno) %>% dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), aes(x=((Cno-3)/2)+2009, y=median_inc), col="blue")+
  facet_wrap(factor(sp)~., 
  nrow=3)+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for candidate species")+
  theme_bw()

#png("spagplot_pointdendro_sp.png", width=12, height=8, units="in", res=300)
spagplot_ind
#dev.off()


spagplot_pointsp<-ggplot() +
  #species plots
  geom_line(data=point_sp %>% group_by(Cno, sp) %>% dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc, 
  group=factor(sp), 
  col=factor(sp)))+
  geom_line(data=point_sp %>% group_by(Cno) %>% dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="black", size=2)+
  scale_color_viridis_d()+
  guides(col=guide_legend(title="species"))+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for candidate species")+
  theme_bw()

#png("spagplot_pointdendro_spsum.png", width=4, height=4, units="in", res=300)
spagplot_pointsp
#dev.off()

```
```{r elevation, echo=F}
#elevation data
hkk_elev<-read.table("data/HKK-other/CTFSElev_hkk.rdata")


```

```{r maps, echo=F}
# make maps of dendroband individuals of species
# base map is habitat map

#habitat data
habitat<-read.csv("data/HKK-other/HKK_habtype(in).csv")

#plot a tile map of habitat types
#png("dendro_spmap.png", width=16, height=8, units="in", res=300)
ggplot()+
  geom_tile(data=habitat, aes(x=x, y=y, fill=factor(hab)))+
  scale_fill_viridis_d(option="E", direction=-1)+
  geom_point(data=point_sp_tree,
  alpha=0.5, aes(x=X, y=Y, size=as.numeric(DBH.04)))+
  theme_minimal()+
  facet_wrap(factor(SPCODE.UPDATE)~.)+
  coord_fixed()
#dev.off()

habitat<-habitat %>%
  dplyr::mutate(Col = x/20,
                Row = y/20)

trees<-merge(trees, select(habitat, -c(X, x, y)), by=c("Col", "Row"), all.x=T)


```

```{r individual species, results='asis', echo=F}

p1<-ggplot()+
  geom_tile(data=habitat, aes(x=x, y=y, fill=factor(hab)))+
  scale_fill_viridis_d(option="E", direction=-1)+
  geom_point(data=point_sp_tree %>% filter(SPCODE.UPDATE=="CROTRO"),
  alpha=0.5, aes(x=X, y=Y, size=as.numeric(DBH.04), text=paste0("Tag: ",Tag)))+
  theme_minimal()+
  #facet_wrap(factor(SPCODE.UPDATE)~.)+
  coord_fixed()

ggplotly(p1, tooltip = c("text", "size"))

sps<-c("HOPEOD", "TETRNU", "SACCLI", "POLYVI")

for(i in 1:4){

p<-ggplot()+
  geom_tile(data=habitat, aes(x=x, y=y, fill=factor(hab)))+
  scale_fill_viridis_d(option="E", direction=-1)+
  geom_point(data=point_sp_tree %>% 
  #filter(SPCODE.UPDATE=="HOPEOD"),
  filter(SPCODE.UPDATE==sps[i]),
  alpha=0.5, aes(x=X, y=Y, size=as.numeric(DBH.04), text=paste0("Tag: ",Tag)))+
  theme_minimal()+
  ggtitle(paste0("species: ", sps[i]))+
  #facet_wrap(factor(SPCODE.UPDATE)~.)+
  coord_fixed()

print(htmltools::tagList(ggplotly(p, tooltip = c("text", "size"))))
}

```

```{r plot of selected trees for 4 species, results='asis', echo=F}

pdendro_trees<-read.csv("point_dendro_trees.csv")

sp4<-c("HOPEOD", "TETRNU", "SACCLI", "POLYVI")

pdendro_confirm<-pdendro_trees %>%
filter(sp %in% sp4) %>%
filter(confirm4=="y") 

#filter the main dataset with these tags

point_trees<-trees %>%
filter(Tag %in% pdendro_confirm$Tag)

#plot these on the habitat map

p <- ggplot()+
  geom_tile(data=habitat, aes(x=x+10, y=y+10, fill=factor(hab)), alpha=0.5)+
  scale_fill_viridis_d(option="E", direction=-1)+
  geom_contour(data=hkk_elev, aes(x=col.x, y=col.y, z=col.elev), col="black")+
  geom_point(data=point_trees, aes(x=X, y=Y, 
  col=factor(SPCODE.UPDATE),
  size=as.numeric(DBH.04), 
  text=paste0("Tag: ",Tag)))+
  theme_minimal()+
  coord_fixed()+
  ggtitle("selected trees for 4 species design")+
  xlab("") + ylab("")+
  guides(fill="none", size="none",
  col=guide_legend(title="species"))


png("point_dendro_sp4.png", width=12, height=7, units="in", res=300)
p+geom_text(data=point_trees, aes(x=X, y=Y, label=Tag), size=3)
dev.off()

ggplotly(p, tooltip = c("text", "size"))

```

```{r plot of selected trees for 8 species, results='asis', echo=F}

pdendro_trees<-read.csv("point_dendro_trees.csv")

pdendro_confirm<-pdendro_trees %>%
#filter(sp %in% sp4) %>%
filter(confirm8=="y") 

#filter the main dataset with these tags

point_trees<-trees %>%
filter(Tag %in% pdendro_confirm$Tag)

#plot these on the habitat map

p <- ggplot()+
  geom_tile(data=habitat, aes(x=x+10, y=y+10, fill=factor(hab)), alpha=0.5)+
  scale_fill_viridis_d(option="E", direction=-1)+
  geom_contour(data=hkk_elev, aes(x=col.x, y=col.y, z=col.elev), col="black")+
  geom_point(data=point_trees, aes(x=X, y=Y, 
  col=factor(SPCODE.UPDATE),
  size=as.numeric(DBH.04), 
  text=paste0("Tag: ",Tag)))+
  theme_minimal()+
  coord_fixed()+
  ggtitle("selected trees for 8 species design")+
  xlab("") + ylab("")+
  guides(fill="none", size="none",
  col=guide_legend(title="species"))

png("point_dendro_sp8.png", width=12, height=7, units="in", res=300)
p+geom_text(data=point_trees, aes(x=X, y=Y, label=Tag), size=3)
dev.off()


ggplotly(p, tooltip = c("text", "size"))

```
