---
title: "Drought vulnerability of tree growth"
author: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## HKK climate

```{r echo = FALSE, message=F, warning=F}

#load libraries
library(tidyverse)
library(lubridate)
library(httr)
library(janitor)

#reading the GitHub PAT (stored privately and locally)
#pat<-as.character(read.table("../data/HKK-dendro/git_pat.txt")[1,1])

# remotes:::download("DendroByBand.RData",
#                    "https://raw.githubusercontent.com/forestgeo/HKK-dendrobands/main/data/modified_data/DendroByBand.RData",
#                    auth_token = pat)

load("growth-precip-thailand/data/HKK-dendro/DendroByBand.RData")


dendrobyband<-merge(dendrobyband, trees, by="Tag")

hkk_OBSID$year<-year(hkk_OBSID$Date2)
hkk_OBSID$month<-month(hkk_OBSID$Date2)
hkk_OBSID$day<-day(hkk_OBSID$Date2)

#correcting two sets of wrong dates

hkk_OBSID$year[hkk_OBSID$year==2209]<-2009
hkk_OBSID$year[hkk_OBSID$month==1 & hkk_OBSID$Cno==5]<-2011

dendrobyband<-merge(dendrobyband, hkk_OBSID, by=c("OBSID", "Cno", "Date2", "Tag"))

dendrobyband$Date2<-as.Date(paste0(dendrobyband$year,"-", dendrobyband$month, "-", dendrobyband$day))

#getting climate data for all


#CHIRPS data ----

# CHIRPS data GEE code here - https://code.earthengine.google.com/894597bd093906fb0ff82320f29c0842


#chirps_hkk<-read.csv("../data/climate/CHIRPS_from_GEE.csv")
chirps_hkk<-read.csv("growth-precip-thailand/data/climate/CHIRPS_from_GEE.csv")
colnames(chirps_hkk)[1]<-"time"

#making dates manageable
chirps_hkk<- chirps_hkk %>%
  dplyr::mutate(time=as.Date(time, format = "%b %d, %Y"),
                year=year(time),
                month=month(time))

census_int<-dendrobyband%>%
  group_by(Cno) %>%
  dplyr::summarise(start=as.Date(min(Date2, na.rm = T)),
                   end=as.Date(max(Date2, na.rm=T)))#%>%
  #dplyr::mutate(type=ifelse(Cno %in% wet_census, "wet", "dry"))

spei_hkk<-read.csv("growth-precip-thailand/data/climate/SPEI_HKK_from_GEE.csv")
colnames(spei_hkk)[1]<-"time"

#making dates manageable
spei_hkk<- spei_hkk %>%
  dplyr::mutate(time=as.Date(time, format = "%b %d, %Y"),
                year=year(time),
                month=month(time))


pre_yr_census<-ggplot()+
  geom_line(data=chirps_hkk, aes(x=time, y=precipitation), col="blue", alpha=0.5)+
  geom_line(data=spei_hkk, aes(x=time, y=(100*SPEI_01_month-250)), col="red")+
  geom_rect(data=census_int, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), 
              fill = "grey10", alpha = 0.5) +
  geom_text(data=census_int, aes(x=start, y=500, 
                                 label= paste0("C", 1:29), angle=90), size=2)+
   scale_y_continuous(    # Features of the first axis
     name = "monthly rainfall (mm)",
     
     # Add a second axis and specify its features
     sec.axis = sec_axis(~(.+250)*0.01, name="SPEI"))+
  xlab("")+theme_bw()+ ylab("total monthly precipitation (mm) from CHIRPS")+
  ggtitle("HKK dendroband censuses and climate")+
  #scale_x_continuous(n.breaks=15)+
  theme(axis.text.x = element_text(angle=45))


#png("../doc/display/census_precip.png", width=6, height=3, res=300, units="in") 
#png("../doc/display/census_precip.png", width=6, height=3, res=300, units="in") 
pre_yr_census
#dev.off()



#rainfall per year

#-----------------Decisions on climate data-----------------------=
# Summarising climate data to relevant time window for SCBI
# As per issue #42 and KAT pub https://onlinelibrary-wiley-com.smithsonian.idm.oclc.org/doi/full/10.1111/gcb.15934
# HKK best climate variables are:
# PPT - previous Sep to current June (it is actually precipitation day freq, but using sum now)
# Tmax - current Apr to Oct
#---------------------------------------------------------------=

#applying these decisions and rescaling

#mean annual precip from 1981 to 2023 is 1698.4

#code - https://code.earthengine.google.com/b0eda787f2e1ba578bbf50a8a9d04843

climate_data_yr<-chirps_hkk %>%
  group_by(year) %>%
  summarise(
    tot_precip=sum(precipitation),
    pre_SeptoDec=sum(precipitation[month>=9]), #Sep to Dec precip for each year
    pre_JantoJun=sum(precipitation[month<=6]) #Jan to June precip for each year
    #tmx_window=sum(value[variable == "tmx"& month %in% 4:10])
)%>% #sum of potential evapotranspiration for current May to July
  mutate(
    pre_window=pre_JantoJun+lag(pre_SeptoDec), #adding prev year's June to Dec and current year's Jan to June
    tot_pre_diff=tot_precip-1698.4
    )

#standard deviation is 254.06

precip_plot<-ggplot(climate_data_yr)+
  geom_bar(aes(x=year, y=tot_pre_diff), stat="identity")+
  ylab("difference from 40-year mean (mm)")+
  geom_hline(yintercept = c(254.06, -254.06), lty=2)+
  theme_bw()
precip_plot




# library
library(ggridges)
library(ggplot2)
library(viridis)
library(hrbrthemes)

chirps_hkk$year_fac<-as.character(chirps_hkk$year)
chirps_hkk$year_fac<-factor(chirps_hkk$year)


# Plot
ggplot(chirps_hkk, aes(x = precipitation, y = year_fac, 
                       fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "rainfall", option = "C") +
  labs(title = 'Rainfall in HKK') +
  #theme_ipsum() +
  theme_bw()+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )



```
```{r echo=F}

#remove all data with decimal errors, misplaced decimal

dendro.data<-dendrobyband %>%
  dplyr::rename(sp=SPCODE.UPDATE)%>%
  mutate(year=year(Date2)) %>%
  filter(is.na(DBH1_flag), DBH1_error=="none",
         win.decimal.error=="none", is.na(win.flag))%>%
  group_by(Cno, sp, Tag) %>%
  dplyr::summarise(calcDBH=calcDBH[which(n.dendro==min(n.dendro))],
                   Date2=Date2[which(n.dendro==min(n.dendro))],
                   n.dendro=min(n.dendro), #which dendroband is it from?
                   Cii=max(Cii, na.rm=T))

dbh.data<-dendrobyband %>%
  dplyr::rename(sp=SPCODE.UPDATE)%>%
  mutate(year=year(Date2)) %>%
  filter(is.na(dbh.flag), dbh.decimal.error=="none")%>%
  group_by(Cno, sp, Tag) %>%
  dplyr::summarise(dbh=DbhDendro[which(n.dendro==min(n.dendro))],
                   Date2=Date2[which(n.dendro==min(n.dendro))],
                   n.dendro=min(n.dendro),
                   Cii=max(Cii, na.rm=T))


  
```
```{r long-term growth rates}

# remotes:::download("../data/HKK-dendro/stem1.RData",
#                    "https://raw.githubusercontent.com/forestgeo/HKK-tree-growth-data/main/data/Census/raw_data/hkk.stem1.rdata",
#                    auth_token = pat)
# remotes:::download("../data/HKK-dendro/stem2.RData",
#                    "https://raw.githubusercontent.com/forestgeo/HKK-tree-growth-data/main/data/Census/raw_data/hkk.stem2.rdata",
#                    auth_token = pat)
# remotes:::download("../data/HKK-dendro/stem3.RData",
#                    "https://raw.githubusercontent.com/forestgeo/HKK-tree-growth-data/main/data/Census/raw_data/hkk.stem3.rdata",
#                    auth_token = pat)
# remotes:::download("../data/HKK-dendro/stem4.RData",
#                    "https://raw.githubusercontent.com/forestgeo/HKK-tree-growth-data/main/data/Census/raw_data/hkk.stem4.rdata",
#                    auth_token = pat)

load("growth-precip-thailand/data/HKK-dendro/stem1.RData")
load("growth-precip-thailand/data/HKK-dendro/stem2.RData")
load("growth-precip-thailand/data/HKK-dendro/stem3.RData")
load("growth-precip-thailand/data/HKK-dendro/stem4.RData")

hkk_census<-bind_rows(hkk.stem1, hkk.stem2, hkk.stem3, hkk.stem4)

hkk_census <- hkk_census %>%
  filter(status=="A")%>%
  filter(tag %in% dendro.data$Tag)%>%
  group_by(tag, StemTag)%>%
  dplyr::mutate(dbhmin1 = dplyr::lag(dbh, n=1, default=NA, order_by=StemTag),
                inc_annual = (dbh-dbhmin1)/5)%>%
  filter(!is.na(dbhmin1))%>%
  #average increment in cm
  dplyr::summarise(avg_inc = mean(inc_annual/10, na.rm=T),
                   sd_inc = sd(inc_annual/10, na.rm=T))
                  

census_top4<-bind_rows(hkk.stem1, hkk.stem2, hkk.stem3, hkk.stem4) %>%
  filter(status=="A")%>%
  filter(sp %in% c("SACCLI", "HOPEOD", "TETRNU", "POLYVI"))%>%
  filter(tag==StemTag) %>%
  group_by(sp, tag)%>%
  dplyr::mutate(dbhmin1 = dplyr::lag(dbh, n=1, default=NA, order_by=tag),
                inc_annual = (dbh-dbhmin1)/5)%>%
  filter(!is.na(dbhmin1))%>%
  #average increment in cm
  dplyr::summarise(avg_inc = mean(inc_annual/10, na.rm=T),
                   sd_inc = sd(inc_annual/10, na.rm=T))


#since dendrobands are installed on trees with tag==StemTag
hkk_census<-hkk_census %>%
filter(tag==StemTag)

#there are 2271 trees in this dataset.

inc_census<-ggplot(data = hkk_census, aes(x=avg_inc)) +
  geom_density(alpha=0.5) +
  xlab("mean annual increment (cm)")+
  theme_bw()

png("growth-precip-thailand/doc/display/census_increment.png", width=4, height=4, units="in", res=300)
inc_census
dev.off()

#plot average increment for the top 4 species
hkk_census2<-hkk_census %>%
dplyr::rename(Tag=tag)

hkk_census2<-merge(hkk_census2, trees, by="Tag")
hkk_census2<-hkk_census2 %>%
dplyr::rename(sp=SPCODE.UPDATE)

png("growth-precip-thailand/doc/display/census_increment_species.png", width=4, height=4, units="in", res=300)
ggplot(hkk_census2 %>% filter(sp %in% c("SACCLI", "HOPEOD", "TETRNU", "POLYVI")), 
aes(x= factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y = avg_inc, fill=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")))) +
  geom_violin(position = "dodge")+ 
    geom_boxplot(position="dodge", col="black", fill="white", width=0.1)+
  scale_fill_viridis_d()+
  labs(title = 'tree growth in HKK from census', 
  y="Annualised diameter increment (cm)", x="species") +
  theme_bw()+
  geom_text(data=hkk_census2 %>% filter(sp %in% c("SACCLI", "HOPEOD", "TETRNU", "POLYVI")) %>% group_by(sp) %>% dplyr::summarise(n=n()),
   aes(x=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y=2.2, 
  label=n))+
  #geom_vline(xintercept=0, lty=2)+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
dev.off()

png("growth-precip-thailand/doc/display/census_increment_species_alltrees.png", width=4, height=4, units="in", res=300)
ggplot(census_top4, 
aes(x= factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y = avg_inc, fill=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")))) +
  geom_violin(position = "dodge")+ 
    geom_boxplot(position="dodge", col="black", fill="white", width=0.1)+
  scale_fill_viridis_d()+
  labs(title = 'tree growth in HKK (all stems)', 
  y="Annualised diameter increment (cm)", x="species") +
  theme_bw()+
  geom_text(data=census_top4 %>% group_by(sp) %>% dplyr::summarise(n=n()),
   aes(x=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y=2.2, 
  label=n))+
  #geom_vline(xintercept=0, lty=2)+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
dev.off()

```

```{r calculating increments for all years}
  
hkk_census<-hkk_census %>%
rename(Tag=tag)  

#add long-term increment to dendro data
dendro.data<-merge(dendro.data, hkk_census, by="Tag", all.x=T)
dbh.data<-merge(dbh.data, hkk_census, by="Tag", all.x=T)

#making increments for each year

alt_census<-c(1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29)

dendro_inc<- dendro.data %>%
  filter(Cno %in% alt_census)%>%
  arrange(Cno)%>%
  group_by(Tag) %>% #grouping by treeID to calculate increment
  dplyr::mutate(calcDBH_min1=dplyr::lag(calcDBH, n=1, default=NA, order_by=Tag),
  n.dendro_diff=n.dendro-dplyr::lag(n.dendro, n=1, default=NA, order_by=Tag),
         cii_min1=dplyr::lag(Cii, n=1, default=NA, order_by=Tag),
         tdif=difftime(Date2, dplyr::lag(Date2, n=1, default=NA, order_by=Tag), units = "days"),
         inc=calcDBH-calcDBH_min1,
         inc_annual=(inc/as.numeric(tdif))*365,
         inc.time=Cno-dplyr::lag(Cno, n=1, default=NA, order_by=Tag),
         #removing increment value if the previous measure was before the last year
         inc_annual=ifelse(inc.time==2, inc_annual, NA),
         treeID=paste0("HKK.", Tag))%>%
  filter(!is.na(inc))%>%
  filter(!is.na(inc_annual))%>%
  ungroup()%>%
  dplyr::mutate(
    diainc.scaled = scale(inc_annual),
    out.inc = ifelse(abs(diainc.scaled)>3, 1, 0))%>%
  filter(out.inc==0)


dbh_inc<- dbh.data %>%
  filter(Cno %in% alt_census)%>%
  arrange(Cno)%>%
  group_by(Tag) %>% #grouping by treeID to calculate increment
  dplyr::mutate(dbh_min1=dplyr::lag(dbh, n=1, default=NA, order_by=Tag),
  n.dendro_diff=n.dendro-dplyr::lag(n.dendro, n=1, default=NA, order_by=Tag),
         cii_min1=dplyr::lag(Cii, n=1, default=NA, order_by=Tag),
         tdif=difftime(Date2, dplyr::lag(Date2, n=1, default=NA, order_by=Tag), units = "days"),
         inc=dbh-dbh_min1,
         inc_annual=(inc/as.numeric(tdif))*365,
         inc.time=Cno-dplyr::lag(Cno, n=1, default=NA, order_by=Tag),
         #removing increment value if the previous measure was before the last year
         inc_annual=ifelse(inc.time==2, inc_annual, NA),
         treeID=paste0("HKK.", Tag))%>%
  filter(!is.na(inc))%>%
  filter(!is.na(inc_annual))%>%
  ungroup()%>%
  dplyr::mutate(
    diainc.scaled = scale(inc_annual),
    out.inc = ifelse(abs(diainc.scaled)>3, 1, 0))%>%
  filter(out.inc==0)

```

```{r comparing dbh and dendro and identify outliers, echo=F}

#merge dbh and dendro data by Tag and Cno
inc_all<-merge(dendro_inc, dbh_inc, by=c("sp", "Tag", "Cno"), all=T)

#Perpendicular distance from point 'a' to a line with 'slope' and 'intercept'
dist_point_line <- function(a, slope, intercept) {
    b = c(1, intercept+slope)
    c = c(-intercept/slope,0)       
    v1 <- b - c
    v2 <- a - b
    m <- cbind(v1,v2)
    return(abs(det(m))/sqrt(sum(v1*v1)))
}

inc_all<-inc_all %>%
  dplyr::rename(inc_annual.dendro=inc_annual.x, 
  inc_annual.dbh=inc_annual.y,
  band.diff.dendro=n.dendro_diff.x,
  band.diff.dbh=n.dendro_diff.y) %>%
  #split into three size classes
  dplyr::mutate(size_class= ifelse(dbh<35, "small",
  ifelse(dbh<70, "medium", "large")),
  size_class=factor(size_class, levels=c("small", "medium", "large"))
  #find the deviation of the increment from the 1:1 line
  )%>%
  select(sp, Tag, Cno, inc_annual.dendro, inc_annual.dbh, dbh, 
  size_class, band.diff.dbh, band.diff.dendro)

#using the distance to the line
dev.1<-mapply(function(x)dist_point_line(c(inc_all$inc_annual.dendro[x], inc_all$inc_annual.dbh[x]), 1, 0), x=1:nrow(inc_all))
inc_all$dev.1<-dev.1


#compare dbh and dendro increments for all species

cor.all<-cor(inc_all$inc_annual.dendro, inc_all$inc_annual.dbh, use="complete.obs")

dbh_dendro_all<-ggplot(inc_all, aes(x=inc_annual.dendro, y=inc_annual.dbh, col=factor(band.diff.dendro+band.diff.dbh, levels=c(0, 1, 2))))+
  geom_point(alpha=0.5)+
  geom_abline(intercept=0, slope=1)+
  scale_color_manual(values=c("black", "orange", "tomato", "grey40"))+
  xlab("dendroband increment (cm)")+
  ylab("dbh increment (cm)")+
  geom_rug(alpha=0.3)+
  geom_text(aes(x=2, y=4, label = paste0("r = ", round(cor.all,3))), vjust = -0.5) +
  guides(col=guide_legend(title="band_diff"))+
  ggtitle("comparison of dbh and dendro increments")+
  theme_bw()


#plot distribution of deviations

pct.0.5<-round(sum(inc_all$dev.1>=0.5, na.rm=T)*100/nrow(inc_all),2)
pct.1<-round(sum(inc_all$dev.1>=1, na.rm=T)*100/nrow(inc_all),2)
pct.2<-round(sum(inc_all$dev.1>=2, na.rm=T)*100/nrow(inc_all),2)
pct.0.1<-round(sum(inc_all$dev.1>=0.1, na.rm=T)*100/nrow(inc_all),2)


png("growth-precip-thailand/doc/display/deviation_distribution.png", width=4, height=4, units="in", res=300)
ggplot()+
  geom_density(data=inc_all, aes(x=dev.1), size=1.2)+
  ggtitle("deviation of dendroband and tape-based \nincrements from each other")+
  geom_vline(xintercept=c(0.1, 0.5, 1, 2), lty=2, col="orange")+
  geom_text(aes(x=c(0.1, 0.5, 1, 2), y=5, 
  label = paste0(">",c(0.1, 0.5, 1, 2), " = ", c(pct.0.1, pct.0.5, pct.1, pct.2), "%")), 
  angle=90, vjust = 1, size=2)+
  xlab("distribution of deviations from 1:1 line")+
  theme_bw()
dev.off()
```

```{r separating outliers, echo=F}

#outlier dataframe
outliers<-inc_all %>% filter(dev.1>=0.5)
write.csv(outliers, "growth-precip-thailand/data/HKK-dendro/inc_outliers.csv", row.names=F)

#clean dataframe

dendro_inc<-merge(dendro_inc, inc_all %>% select(Tag, Cno, sp, dev.1), 
by=c("Tag", "Cno", "sp"), all.x=T)

dendro_inc_clean<-dendro_inc %>% filter(dev.1<0.5)

#plot increments from dbh and dendro data with outliers removed

cor.noouts<-dendro_inc_clean %>%
dplyr::summarise(cor=cor(inc_annual.dendro, inc_annual.dbh, use="complete.obs"))
cor.noouts<-cor.noouts$cor[1]

dbh_dendro_noouts<-ggplot(inc_all %>% filter(dev.1<0.5), aes(x=inc_annual.dendro, y=inc_annual.dbh, col=factor(band.diff.dendro+band.diff.dbh, levels=c(0, 1, 2))))+
  geom_point(alpha=0.5)+
  geom_abline(intercept=0, slope=1)+
  scale_color_manual(values=c("black", "orange", "tomato", "grey40"))+
  xlab("dendroband increment (cm)")+
  ylab("dbh increment (cm)")+
  geom_rug(alpha=0.3)+
  geom_text(aes(x=2, y=4, label = paste0("r = ", round(cor.noouts,3))), vjust = -0.5) +
  guides(col=guide_legend(title="band_diff"))+
  ggtitle("dbh and dendro increments (outliers removed)")+
  theme_bw()
dev.off()

library(gridExtra)
png("growth-precip-thailand/doc/display/dbh_dendro_compare_all.png", width=8, height=4, units="in", res=300)
grid.arrange(dbh_dendro_all, dbh_dendro_noouts, ncol=2)
dev.off()

```
```{r compare deviations by species and size, echo=F}

ggplot(inc_all %>% filter(sp.x %in% c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), aes(x=inc_annual.x, y=inc_annual.y, 
col=factor(sp.x, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))))+
  geom_point()+
  scale_color_viridis_d()+
  geom_abline(intercept=0, slope=1)+
  xlab("dendroband increment (cm)")+
  ylab("dbh increment (cm)")+
  guides(col=guide_legend(title="species"))+
  ggtitle("comparison of dbh and dendro increments")+
  theme_bw()


#split this by size classes

cors.size<-inc_all %>% 
filter(!is.na(size_class))%>%
  group_by(size_class) %>% 
  dplyr::summarise(cor=cor(inc_annual.dendro, inc_annual.dbh, use="complete.obs"))

png("growth-precip-thailand/doc/display/dbh_dendro_compare_size.png", width=8, height=4, units="in", res=300)
ggplot(inc_all %>% filter(!is.na(size_class)), aes(x=inc_annual.dendro, y=inc_annual.dbh, 
col=size_class))+
  geom_point(alpha=0.5)+
  geom_abline(intercept=0, slope=1)+
  xlab("dendroband increment (cm)")+
  ylab("dbh increment (cm)")+
  facet_grid(.~size_class)+
  geom_text(data=cors.size, aes(x=2, y=4, label = paste0("r = ", round(cor,3))), vjust = -0.5) +
  guides(col=guide_legend(title="size class"))+
  ggtitle("comparison of dbh and dendro increments")+
  theme_bw()
dev.off()

```

```{r species wise increments, echo=F}

top4<-dendro_inc %>%
filter(sp %in% c("SACCLI", "HOPEOD", "TETRNU", "POLYVI"))

top4_noouts<-dendro_inc_clean %>%
filter(sp %in% c("SACCLI", "HOPEOD", "TETRNU", "POLYVI"))

#individual panels using facet_wrap
spagplot_ind<-ggplot() +
  geom_line(data = top4, aes(x=((Cno-3)/2)+2009, y=inc_annual, group=Tag), alpha=0.5) +
  geom_line(data=top4 %>% group_by(Cno) %>% dplyr::summarise(mean_inc=mean(inc_annual, na.rm=T)), aes(x=((Cno-3)/2)+2009, y=mean_inc), col="red")+
  geom_line(data=top4 %>% group_by(Cno) %>% dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), aes(x=((Cno-3)/2)+2009, y=median_inc), col="blue")+
  facet_wrap(factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))~., 
  nrow=2)+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for top 4 species")+
  theme_bw()

png("growth-precip-thailand/doc/display/spaghetti_top4_ind.png", width=8, height=8, units="in", res=300)
spagplot_ind
dev.off()

#individual panels using facet_wrap for the no outs dataset
spagplot_ind_noouts<-ggplot() +
  geom_line(data = top4_noouts, aes(x=((Cno-3)/2)+2009, y=inc_annual, group=Tag), alpha=0.5) +
  geom_line(data=top4_noouts %>% group_by(Cno) %>% dplyr::summarise(mean_inc=mean(inc_annual, na.rm=T)), aes(x=((Cno-3)/2)+2009, y=mean_inc), col="red")+
  geom_line(data=top4_noouts %>% group_by(Cno) %>% dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), aes(x=((Cno-3)/2)+2009, y=median_inc), col="blue")+
  facet_wrap(factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))~., 
  nrow=2)+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for top 4 species (no outliers)")+
  theme_bw()

png("growth-precip-thailand/doc/display/spaghetti_top4_ind_noouts.png", width=8, height=8, units="in", res=300)
spagplot_ind_noouts
dev.off()


#spaghetti plot of all species together

spagplot_top4<-ggplot() +
  #species plots
  geom_line(data=top4 %>% group_by(Cno, sp) %>% dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc, 
  group=factor(sp,levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), 
  col=factor(sp,levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))))+
  geom_line(data=top4 %>% group_by(Cno) %>% dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="black", size=2)+
  scale_color_viridis_d()+
  guides(col=guide_legend(title="species"))+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for top 4 species")+
  theme_bw()


png("growth-precip-thailand/doc/display/spaghetti_top4.png", width=4, height=4, units="in", res=300)
spagplot_top4
dev.off()

#spaghetti plot for top 10 species

sp_top10<-c("SACCLI", "HOPEOD", "TETRNU", "POLYVI", "VATIHA", 
"DIPTAL", "ALPHVE", "GARCSP", "GARUPI", "NEOLOB")

spagplot_top10<-ggplot()+
  #species plots
  geom_line(data=dendro_inc %>% filter(sp %in% sp_top10)%>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc, 
  group=sp, col=sp))+
  #mean of all trees
  geom_line(data=dendro_inc %>% filter(sp %in% sp_top10)%>% group_by(Cno) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="black", size=2)+
  #mean of species
  geom_line(data=dendro_inc %>% filter(sp %in% sp_top10)%>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)) %>%
  ungroup()%>%
  group_by(Cno) %>% dplyr::summarise(median_inc=mean(median_inc, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="grey40", size=0.8)+
  scale_color_viridis_d()+
  guides(col=guide_legend("species"))+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for top 10 species")+
  theme_bw()

png("growth-precip-thailand/doc/display/spaghetti_top10.png", width=4, height=4, units="in", res=300)
spagplot_top10
dev.off()

#spaghetti plot for top 10 species with outliers removed

sp_top10<-c("SACCLI", "HOPEOD", "TETRNU", "POLYVI", "VATIHA", 
"DIPTAL", "ALPHVE", "GARCSP", "GARUPI", "NEOLOB")

spagplot_top10_noouts<-ggplot()+
  #species plots
  geom_line(data=dendro_inc_clean %>% filter(sp %in% sp_top10)%>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc, 
  group=sp, col=sp))+
  #mean of all trees
  geom_line(data=dendro_inc_clean %>% filter(sp %in% sp_top10)%>% group_by(Cno) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="black", size=2)+
  #mean of species
  geom_line(data=dendro_inc_clean %>% filter(sp %in% sp_top10)%>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)) %>%
  ungroup()%>%
  group_by(Cno) %>% dplyr::summarise(median_inc=mean(median_inc, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="grey40", size=0.8)+
  scale_color_viridis_d()+
  guides(col=guide_legend("species"))+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for top 10 species")+
  theme_bw()

png("growth-precip-thailand/doc/display/spaghetti_top10_noouts.png", width=4, height=4, units="in", res=300)
spagplot_top10_noouts
dev.off()

#all species with and without outliers

spagplot_all<-ggplot() +
  #species plots
  geom_line(data=dendro_inc %>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc, 
  group=sp, col=sp))+
  #mean of all trees
  geom_line(data=dendro_inc %>% group_by(Cno) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="black", size=2)+
  #mean of species
  geom_line(data=dendro_inc %>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)) %>%
  ungroup()%>%
  group_by(Cno) %>% dplyr::summarise(median_inc=mean(median_inc, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="grey40", size=0.8)+
  scale_color_viridis_d()+
  guides(col="none", group="none")+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for all species")+
  theme_bw()

png("growth-precip-thailand/doc/display/spaghetti_all.png", width=4, height=4, units="in", res=300)
spagplot_all
dev.off()

spagplot_all_noouts<-ggplot() +
  #species plots
  geom_line(data=dendro_inc_clean %>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc, 
  group=sp, col=sp))+
  #mean of all trees
  geom_line(data=dendro_inc_clean %>% group_by(Cno) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="black", size=2)+
  #mean of species
  geom_line(data=dendro_inc_clean %>% group_by(Cno, sp) %>% 
  dplyr::summarise(median_inc=median(inc_annual, na.rm=T)) %>%
  ungroup()%>%
  group_by(Cno) %>% dplyr::summarise(median_inc=mean(median_inc, na.rm=T)), 
  aes(x=((Cno-3)/2)+2009, y=median_inc), col="grey40", size=0.8)+
  scale_color_viridis_d()+
  guides(col="none", group="none")+
  xlab("year") + ylab("diameter increment (cm)")+
  ggtitle("growth increments for all species (no outs)")+
  theme_bw()

png("growth-precip-thailand/doc/display/spaghetti_all_noouts.png", width=4, height=4, units="in", res=300)
spagplot_all_noouts
dev.off()


png("growth-precip-thailand/doc/display/top4_increments.png", width=8, height=4, units="in", res=300)
ggplot(top4, aes(x = inc_annual, y = factor(((Cno-3)/2)+2009), 
                       fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "growth", option = "H", direction=-1) +
  labs(title = 'tree growth in HKK (cm)', y="year") +
  #theme_ipsum() +
  facet_grid(.~factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")))+
  theme_bw()+
  xlim(-1.5, 1.5)+
  geom_vline(xintercept=0, lty=2)+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
dev.off()


growth_top4<-ggplot(top4, aes(x=factor(((Cno-3)/2)+2009), y=inc_annual,
                                              fill=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")),
                                              color=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))
                                              ))+ 
  geom_violin(position = "dodge")+ 
    geom_boxplot(position="dodge", col="black", fill="white", width=0.1)+
ylab("Annualised diameter increment (cm)")+theme_bw()+
geom_segment(data=top4 %>% 
  group_by(sp, Cno) %>% 
  dplyr::summarise(n=n()/500),
aes(x=factor(((Cno-3)/2)+2009), xend=factor(((Cno-3)/2)+2009), y=-3, yend=n-3, 
fill=factor(sp,levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))), size=3)+
facet_grid(.~factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")))+
  geom_hline(yintercept = 0, lty=3)+
      theme(axis.text.x = element_text(angle=90))+
  ggtitle("HKK dendroband data from 2008 to 2023")+
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  guides(fill=guide_legend(title="species"),
         color=guide_legend(title="species"))+
         xlab("year")
         

png("growth-precip-thailand/doc/display/top4_increments_violin.png", width=8, height=4, units="in", res=300)
growth_top4
dev.off()

growth_top4

growth_top4_sum<-ggplot(top4, aes(x=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y=inc_annual,
                                              fill=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")),
                                              color=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))
                                              ))+ 
  geom_violin(position = "dodge")+ 
    geom_boxplot(position="dodge", col="black", fill="white", width=0.1)+
ylab("Annualised diameter increment (cm)")+
xlab("species")+theme_bw()+
  geom_text(data=top4 %>% group_by(sp) %>% dplyr::summarise(n=n()),
   aes(x=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y=2.2, 
  label=n))+
  geom_hline(yintercept = 0, lty=3)+
  ggtitle("tree growth in HKK from dendrobands")+
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  guides(fill="none",
         color="none")
         

png("growth-precip-thailand/doc/display/top4_increments_sum.png", width=4, height=4, units="in", res=300)
growth_top4_sum
dev.off()

#growth_top4_sum using dbh_inc data

growth_top4_sum_dbh<-ggplot(top4_dbh, aes(x=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y=inc_annual,
                                              fill=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")),
                                              color=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))
                                              ))+ 
  geom_violin(position = "dodge")+ 
    geom_boxplot(position="dodge", col="black", fill="white", width=0.1)+
ylab("Annualised diameter increment (cm)")+
xlab("species")+theme_bw()+
  geom_text(data=top4_dbh %>% group_by(sp) %>% dplyr::summarise(n=n()),
   aes(x=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")), y=2.2, 
  label=n))+
  geom_hline(yintercept = 0, lty=3)+
  ggtitle("tree growth in HKK from tape measure")+
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  guides(fill="none",
         color="none")

png("growth-precip-thailand/doc/display/top4_increments_sum_dbh.png", width=4, height=4, units="in", res=300)
growth_top4_sum_dbh
dev.off()

```

```{r top4 species growth contribution, echo=F}

#calculate contribution of each species to average growth for each year

top4_sum<-top4 %>%
  group_by(Cno) %>%
  dplyr::mutate(tot_inc_all=sum(inc_annual, na.rm=T))%>%
  ungroup()%>%
  group_by(Cno, sp) %>%
  dplyr::summarise(contrib=sum(inc_annual, na.rm=T)/mean(tot_inc_all))

#plot contributions across years

contrib_top4<-ggplot(top4_sum, 
aes(x=factor(((Cno-3)/2)+2009), 
y=contrib, fill=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))))+
  geom_bar(stat="identity")+
  scale_fill_viridis_d()+
  xlab("year")+
  ylab("contribution to total growth")+
  guides(fill=guide_legend(title="species"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle=90))

png("growth-precip-thailand/doc/display/top4_contributions.png", width=4, height=4, units="in", res=300)
contrib_top4
dev.off()

#repeat contributions plot for all species

species_sum <- dendro_inc %>%
  group_by(Cno) %>%
  dplyr::mutate(tot_inc_all=sum(inc_annual, na.rm=T))%>%
  ungroup()%>%
  group_by(Cno, sp) %>%
  dplyr::summarise(contrib=sum(inc_annual, na.rm=T)/mean(tot_inc_all))

#plot contributions across years

contrib_all<-ggplot(species_sum, 
aes(x=factor(((Cno-3)/2)+2009), 
y=contrib, fill=factor(sp)))+
  geom_bar(stat="identity")+
  scale_fill_viridis_d()+
  xlab("year")+
  ylab("contribution to total growth")+
  guides(fill=guide_legend(title="species"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle=90))

png("growth-precip-thailand/doc/display/species_contributions.png", width=12, height=4, units="in", res=300)
contrib_all
dev.off()

```


```{r plot increments old code, echo=F, eval=F}

dendro_2010<- dendro.data.noouts %>%
  filter(Cno %in% c(1, 3, 5))%>%
  group_by(Tag) %>% #grouping by treeID to calculate increment
  mutate(calcDBH_min1=dplyr::lag(calcDBH, n=1, default=NA, order_by=Tag),
         cii_min1=dplyr::lag(Cii, n=1, default=NA, order_by=Tag),
         tdif=difftime(Date2, lag(Date2, n=1, default=NA, order_by=Tag), units = "days"),
         inc=calcDBH-calcDBH_min1,
         inc_annual=(inc/as.numeric(tdif))*365,
         inc.time=Cno-lag(Cno),
         #removing increment value if the previous measure was before the last year
         inc_annual=ifelse(inc.time==2, inc_annual, NA),
         treeID=paste0("HKK.", Tag))%>%
  filter(!is.na(inc))%>%
  filter(!is.na(inc_annual))%>%
  ungroup()%>%
  dplyr::mutate(
    diainc.scaled = scale(inc_annual),
    out.inc = ifelse(abs(diainc.scaled)>3, 1, 0))%>%
  filter(out.inc==0)

quantiles_2009<-quantile(dendro_2010$inc_annual[dendro_2010$Cno==3], 
                         probs=c(0.25, 0.5, 0.75, 1))

quantiles_2010<-quantile(dendro_2010$inc_annual[dendro_2010$Cno==5], 
                         probs=c(0.25, 0.5, 0.75, 1))

dendro_2010_plot<-ggplot(data = dendro_2010, aes(x=inc_annual, group=factor(Cno), fill=factor(Cno), col=factor(Cno))) +
  geom_density(alpha=0.5) +
  scale_color_manual(values=c("forestgreen", "brown"))+
  scale_fill_manual(values=c("forestgreen", "brown"))+
  geom_vline(xintercept=quantiles_2009, col="forestgreen")+
  geom_text(aes(x=0.75, y=1, label="2009"), col="forestgreen", size=3)+
  geom_text(aes(x=0.75, y=1.5, label="2010"), col="brown", size=3)+
  geom_vline(xintercept=quantiles_2010, col="brown")+ 
  xlab("diameter increment (cm)") + ylab("density")+
  guides(col="none", fill="none")+
  theme_bw()


dendro_2015<- dendro.data.noouts %>%
  filter(Cno %in% c(11, 13, 15))%>%
  group_by(Tag) %>% #grouping by treeID to calculate increment
  mutate(calcDBH_min1=dplyr::lag(calcDBH, n=1, default=NA, order_by=Tag),
         cii_min1=dplyr::lag(Cii, n=1, default=NA, order_by=Tag),
         tdif=difftime(Date2, lag(Date2, n=1, default=NA, order_by=Tag), units = "days"),
         inc=calcDBH-calcDBH_min1,
         inc_annual=(inc/as.numeric(tdif))*365,
         inc.time=Cno-lag(Cno),
         #removing increment value if the previous measure was before the last year
         #inc=ifelse(inc.time==1, inc, NA),
         inc_annual=ifelse(inc.time==2, inc_annual, NA),
         treeID=paste0("HKK.", Tag))%>%
  filter(!is.na(inc))%>%
  filter(!is.na(inc_annual))%>%
  ungroup()%>%
  dplyr::mutate(
    diainc.scaled = scale(inc_annual),
    out.inc = ifelse(abs(diainc.scaled)>3, 1, 0))%>%
  filter(out.inc==0)

quantiles_2014<-quantile(dendro_2015$inc_annual[dendro_2015$Cno==13], 
                         probs=c(0.25, 0.5, 0.75, 1))

quantiles_2015<-quantile(dendro_2015$inc_annual[dendro_2015$Cno==15], 
                         probs=c(0.25, 0.5, 0.75, 1))

dendro_2015_plot<-ggplot(data = dendro_2015, aes(x=inc_annual, group=factor(Cno), fill=factor(Cno), col=factor(Cno))) +
  geom_density(alpha=0.5) +
  scale_color_manual(values=c("forestgreen", "brown"))+
  scale_fill_manual(values=c("forestgreen", "brown"))+
  geom_vline(xintercept=quantiles_2014, col="forestgreen")+
  geom_text(aes(x=0.75, y=1, label="2014"), col="forestgreen", size=3)+
  geom_text(aes(x=0.75, y=1.5, label="2015"), col="brown", size=3)+
  geom_vline(xintercept=quantiles_2015, col="brown")+ 
  xlab("diameter increment (cm)") + ylab("density")+
  guides(col="none", fill="none")+
  theme_bw()

dendro_2019<- dendro.data.noouts %>%
  filter(Cno %in% c(19, 21, 23))%>%
  group_by(Tag) %>% #grouping by treeID to calculate increment
  mutate(calcDBH_min1=dplyr::lag(calcDBH, n=1, default=NA, order_by=Tag),
         cii_min1=dplyr::lag(Cii, n=1, default=NA, order_by=Tag),
         tdif=difftime(Date2, lag(Date2, n=1, default=NA, order_by=Tag), units = "days"),
         inc=calcDBH-calcDBH_min1,
         inc_annual=(inc/as.numeric(tdif))*365,
         inc.time=Cno-lag(Cno),
         #removing increment value if the previous measure was before the last year
         #inc=ifelse(inc.time==1, inc, NA),
         inc_annual=ifelse(inc.time==2, inc_annual, NA),
         treeID=paste0("HKK.", Tag))%>%
  filter(!is.na(inc))%>%
  filter(!is.na(inc_annual))%>%
  ungroup()%>%
  dplyr::mutate(
    diainc.scaled = scale(inc_annual),
    out.inc = ifelse(abs(diainc.scaled)>3, 1, 0))%>%
  filter(out.inc==0)

quantiles_2018<-quantile(dendro_2019$inc_annual[dendro_2019$Cno==21], 
                         probs=c(0.25, 0.5, 0.75, 1))

quantiles_2019<-quantile(dendro_2019$inc_annual[dendro_2019$Cno==23], 
                         probs=c(0.25, 0.5, 0.75, 1))

dendro_2019_plot<-ggplot(data = dendro_2019, aes(x=inc_annual, group=factor(Cno), fill=factor(Cno), col=factor(Cno))) +
  geom_density(alpha=0.5) +
  scale_color_manual(values=c("forestgreen", "brown"))+
  scale_fill_manual(values=c("forestgreen", "brown"))+
  geom_vline(xintercept=quantiles_2018, col="forestgreen")+
  geom_text(aes(x=0.75, y=1, label="2018"), col="forestgreen", size=3)+
  geom_text(aes(x=0.75, y=1.5, label="2019"), col="brown", size=3)+
  geom_vline(xintercept=quantiles_2019, col="brown")+ 
  xlab("diameter increment (cm)") + ylab("density")+
  guides(col="none", fill="none")+
  theme_bw()


library(gridExtra)
png("growth-precip-thailand/doc/display/increments_raw.png", width=8, height=4, units="in", res=300)
#grid.arrange(dendro_2010_plot, dendro_2015_plot, dendro_2019_plot, nrow=1)
grid.arrange(dendro_2010_plot, dendro_2015_plot, nrow=1)
dev.off()

```

```{r top4 species drought resistance, echo=F}

#drought years 2010 and 2015
# 2010 - cno 5, 2015 - cno 15

resistance_top4 <- top4_noouts %>%
  filter(Cno %in% c(5, 15))%>%
  group_by(Tag) %>% #grouping by treeID to calculate increment
  dplyr::mutate(
    yr=ifelse(Cno==5, 2010, 2015),
        resistance.div = inc_annual/avg_inc,
         resistance.dif = inc_annual-avg_inc,
         resistance.prop = (inc_annual-avg_inc)/avg_inc)%>%
         ungroup()%>%
  filter(!is.infinite(resistance.div))%>%
         group_by(Cno)%>%
         #making quantiles for each year
         dplyr::mutate(
         quantiles_div=ntile(resistance.div, 4))

#merge with tree attributes

resistance_top4<-merge(resistance_top4, select(trees, -"SPCODE.UPDATE"), by="Tag", all.x=T)

#calculate quantiles for resistance.div for both years

quantiles_2010_top4<-quantile(resistance_top4$resistance.div, 
                         probs=c(0.25, 0.5, 0.75, 1), na.rm=T)
quantiles_2015_top4<-quantile(resistance_2015_top4$resistance.div, 
                         probs=c(0.25, 0.5, 0.75, 1), na.rm=T)


#map of resistance.div quantiles for top 4 species

resistance_div<-ggplot(data = resistance_top4, aes(x=resistance.div)) +
  geom_density(alpha=0.5) +
  facet_grid(.~yr)+
  xlim(-5, 5)+
  xlab("inc/long-term increment")+
  geom_vline(xintercept = c(0,1), lty=2)+
  theme_bw()

png("growth-precip-thailand/doc/display/resistance_div_top4.png", width=6, height=4, units="in", res=300)
resistance_div
dev.off()

resistance_div_sp<-ggplot(data = resistance_top4, 
aes(x=resistance.div, 
col=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI")),
fill=factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))))+
  geom_density(alpha=0.5) +
  facet_grid(factor(sp, levels=c("HOPEOD", "TETRNU", "POLYVI", "SACCLI"))~yr)+
  scale_color_viridis_d()+ scale_fill_viridis_d()+
  guides(col="none", fill="none")+
  xlim(-5, 5)+
  xlab("inc/long-term increment")+
  geom_vline(xintercept = c(0,1), lty=2)+
  theme_bw()

png("growth-precip-thailand/doc/display/resistance_div_top4_sp.png", width=6, height=12, units="in", res=300)
resistance_div_sp
dev.off()


resistance_map<-ggplot(resistance_top4, aes(x=X, y=Y, size=as.numeric(DBH.04), 
col=quantiles_div))+
  geom_point(alpha=0.5)+
   scale_size(range = c(.1, 10), name="DBH (cm)")+
  guides(color=guide_legend(title="resistance"))+
  scale_colour_gradient(low="red", high="blue") +
  facet_grid(sp~yr)+
  theme_minimal()+
  coord_fixed()


png("growth-precip-thailand/doc/display/resistance_map_top4.png", width=9, height=8, units="in", res=300)
resistance_map
dev.off()


```


```{r drought resistance}

dec_williams<-read.csv("growth-precip-thailand/data/HKK-dendro/species.csv")

dec_williams<-dec_williams %>%
  filter(n.tree >= 5)

resistance <- dendro_inc_clean %>%
  filter(Cno %in% c(5, 15))%>%
  group_by(Tag) %>% #grouping by treeID to calculate increment
  dplyr::mutate(
    yr=ifelse(Cno==5, 2010, 2015),
        resistance.div = inc_annual/avg_inc,
         resistance.dif = inc_annual-avg_inc,
         resistance.prop = (inc_annual-avg_inc)/avg_inc)%>%
         ungroup()%>%
  filter(!is.infinite(resistance.div))%>%
         group_by(Cno)%>%
         #making quantiles for each year
         dplyr::mutate(
         quantiles_div=ntile(resistance.div, 4),
         quantiles_dif=ntile(resistance.dif, 4),
         quantiles_prop=ntile(resistance.prop, 4))

#merge with tree attributes

resistance<-merge(resistance, select(trees, -"SPCODE.UPDATE"), by="Tag", all.x=T)
resistance<-merge(resistance, dec_williams, by="sp", all.x=T)



#distribution and map

resistance_div<-ggplot(data = resistance, aes(x=resistance.div)) +
  geom_density(alpha=0.5) +
  facet_grid(.~yr)+
  xlim(-5, 5)+
  xlab("inc/long-term increment")+
  ggtitle("resistance values for all trees")+
  geom_vline(xintercept = c(0,1), lty=2)+
  theme_bw()

png("growth-precip-thailand/doc/display/resistance_div.png", width=6, height=4, units="in", res=300)
resistance_div
dev.off()


```

```{r resistance map}

resistance_map<-ggplot(resistance_all, aes(x=X, y=Y, size=as.numeric(DBH.04), col=quantile.div))+
  geom_point(alpha=0.5)+
   scale_size(range = c(.1, 10), name="DBH (cm)")+
  guides(color=guide_legend(title="resistance"))+
  scale_colour_gradient(low="red", high="blue") +
  facet_grid(yr~.)+
  theme_minimal()+
  coord_fixed()

png("growth-precip-thailand/doc/display/resistance_map.png", width=8, height=6, units="in", res=300)
resistance_map
dev.off()
```
```{r basic model}

resistance_all$ciiF<-ordered(resistance_all$cii_min1)

model_2010<-glm(resistance.div ~ calcDBH_min1 + ciiF + williams_dec+
                  calcDBH_min1*ciiF + 
                  calcDBH_min1*williams_dec+
                  ciiF*williams_dec,
                data=resistance_all[resistance_all$yr==2010,])

summary(model_2010)

model_2015<-glm(resistance.div ~ calcDBH_min1 + ciiF + williams_dec+
                  calcDBH_min1*ciiF + 
                  calcDBH_min1*williams_dec+
                  ciiF*williams_dec,
                data=resistance_all[resistance_all$yr==2015,])

summary(model_2015)


summary(model_2019)



resistance_model<-resistance_all %>%
  select(resistance.div, calcDBH_min1, ciiF, williams_dec, yr, quantile)

resistance_model<-resistance_model[complete.cases(resistance_model),]


library(lme4)
library(nlme)
model_all<-lm(resistance.div ~ calcDBH_min1 + ciiF + williams_dec+
                  calcDBH_min1*ciiF + 
                  calcDBH_min1*williams_dec+
                  ciiF*williams_dec + yr,
                data=resistance_model,
                )

model_all
anova(model_all)


model_all_cat<-lme(quantile ~ calcDBH_min1 + cii_min1 + williams_dec+
                  calcDBH_min1*cii_min1 + 
                  calcDBH_min1*williams_dec+
                  cii_min1*williams_dec,
                random=~1|yr,
                data=resistance_model)

model_all_cat
anova(model_all_cat)
```

```{r predictions, echo=F}

library(sjPlot)

plot_model(model_all, type="pred", terms=c("ciiF","williams_dec"), show.data = T)
plot_model(model_all, type="pred", terms=c("cii_min1"), show.data = T)
plot_model(model_all, type="pred", terms=c("williams_dec"), show.data = T)
plot_model(model_all, type="pred", terms=c("calcDBH_min1"), show.data = T)


plot_model(model_all, type = "est")+
  theme_bw()+ylim(c(-0.25, 0.25))+
  geom_hline(yintercept = 0)

plot_model(model_all_cat, type = "est")+
  theme_bw()+ylim(c(-0.25, 0.25))+
  geom_hline(yintercept = 0)

plot_model(model_all_cat, type="pred", terms=c("calcDBH_min1","williams_dec"), show.data = T)
  


# Create a new data frame for predictions
new_data <- expand.grid(
  calcDBH_min1 = seq(min(resistance_model$calcDBH_min1), max(resistance_model$calcDBH_min1), length.out = 100),
  cii_min1 = seq(min(resistance_model$cii_min1), max(resistance_model$cii_min1), length.out = 100),
  williams_dec = seq(min(resistance_model$williams_dec), max(resistance_model$williams_dec), length.out = 100)
)

# Generate predictions
new_data$predicted <- predict(model_all, newdata = new_data, level = 0)

# Create the plot
ggplot(resistance_model, aes(x = williams_dec, y = resistance.dif)) +
  geom_point() +
  geom_line(data = new_data[new_data$cii_min1==2,], aes(y = predicted)) +
  theme_minimal() +
  labs(x = "Deciduousness", y = "Drought resistance", title = "Predictions from LME Model")


```




##Distribution of data with size, exposure and deciduousness

```{r data distribution, echo=F}

#growth data all years ridge plot
png("growth-precip-thailand/doc/display/growth_allyrs2.png", width=4, height=4, units="in", res=300)
ggplot(dendro_inc, aes(x = inc_annual, y = factor(((Cno-3)/2)+2009), 
                       fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "growth", option = "H", direction=-1) +
  labs(title = 'tree growth in HKK (cm)', y="year") +
  #theme_ipsum() +
  theme_bw()+
  xlim(-1.5, 1.5)+
  geom_vline(xintercept=0, lty=2)+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
dev.off()

#2014 data distribution with size, exposure and deciduousness

png("../doc/display/dbh_cii.png", width=4, height=4, units="in", res=300)
ggplot(growth_2014, aes(x = dbh, y = factor(cii), 
                       fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "growth", option = "C", direction=-1) +
  labs(title = 'DBH in 2014 (cm)', y="canopy illumination") +
  #theme_ipsum() +
  theme_bw()+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
dev.off()

length(unique(growth_2014$sp))

png("../doc/display/growth_cii.png", width=4, height=4, units="in", res=300)
ggplot(growth_2014, aes(x = diainc, y = factor(cii), 
                       fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "growth", option = "C", direction=-1) +
  labs(title = 'growth in 2014 (cm)', y="canopy illumination") +
  #theme_ipsum() +
  theme_bw()+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
dev.off()

dec_williams<-read.csv("../data/HKK-dendro/species.csv")

dec_williams<-dec_williams %>%
  filter(n.tree >= 5)

trial<-merge(growth_2014, dec_williams, by="sp")

png("../doc/display/dbh_cii.png", width=4, height=4, units="in", res=300)
ggplot(trial, aes(x = williams_dec, y = factor(Cii), 
                       fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "growth", option = "C", direction=-1) +
  labs(title = 'deciduousness', y="canopy illumination") +
  #theme_ipsum() +
  theme_bw()+
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
dev.off()


```



